-- Migration 004: Research Engine Tables
-- Creates tables for strategy research, backtest jobs, and evolution tracking

-- Strategy ideas generated by the research engine
CREATE TABLE IF NOT EXISTS strategy_ideas (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL, -- TREND_FOLLOWING, MEAN_REVERSION, BREAKOUT, etc.
    symbols TEXT NOT NULL, -- JSON array of symbols
    timeframe TEXT NOT NULL,
    parameters TEXT NOT NULL, -- JSON object
    entry_conditions TEXT NOT NULL, -- JSON array
    exit_conditions TEXT NOT NULL, -- JSON array
    risk_parameters TEXT NOT NULL, -- JSON object
    confidence REAL DEFAULT 0.5,
    status TEXT DEFAULT 'pending', -- pending, running, completed, failed, promoted
    market_regime TEXT, -- trending, ranging, volatile
    parent_strategy_id TEXT, -- For evolved strategies
    generation INTEGER DEFAULT 0,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (parent_strategy_id) REFERENCES strategy_ideas(id)
);

-- Create index for status queries
CREATE INDEX IF NOT EXISTS idx_strategy_ideas_status ON strategy_ideas(status);
CREATE INDEX IF NOT EXISTS idx_strategy_ideas_regime ON strategy_ideas(market_regime);
CREATE INDEX IF NOT EXISTS idx_strategy_ideas_created ON strategy_ideas(created_at);

-- Backtest jobs queue
CREATE TABLE IF NOT EXISTS backtest_jobs (
    id TEXT PRIMARY KEY,
    strategy_id TEXT NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, running, completed, failed, cancelled
    priority INTEGER DEFAULT 5, -- 1-10, lower is higher priority
    candles_count INTEGER DEFAULT 4320, -- 30 days of 5m candles
    results TEXT, -- JSON object with backtest results
    error_message TEXT,
    sharpe_ratio REAL,
    win_rate REAL,
    total_pnl REAL,
    max_drawdown REAL,
    total_trades INTEGER,
    started_at INTEGER,
    completed_at INTEGER,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (strategy_id) REFERENCES strategy_ideas(id)
);

-- Create indexes for job queue
CREATE INDEX IF NOT EXISTS idx_backtest_jobs_status ON backtest_jobs(status);
CREATE INDEX IF NOT EXISTS idx_backtest_jobs_priority ON backtest_jobs(priority);
CREATE INDEX IF NOT EXISTS idx_backtest_jobs_strategy ON backtest_jobs(strategy_id);

-- Strategy performance leaderboard
CREATE TABLE IF NOT EXISTS strategy_performance (
    id TEXT PRIMARY KEY,
    strategy_id TEXT NOT NULL UNIQUE,
    sharpe_ratio REAL DEFAULT 0,
    win_rate REAL DEFAULT 0,
    total_pnl REAL DEFAULT 0,
    max_drawdown REAL DEFAULT 0,
    profit_factor REAL DEFAULT 0,
    total_trades INTEGER DEFAULT 0,
    average_win REAL DEFAULT 0,
    average_loss REAL DEFAULT 0,
    calmar_ratio REAL DEFAULT 0,
    sortino_ratio REAL DEFAULT 0,
    is_active BOOLEAN DEFAULT 0,
    is_promoted BOOLEAN DEFAULT 0, -- Promoted to live trading
    last_backtest_at INTEGER,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (strategy_id) REFERENCES strategy_ideas(id)
);

-- Create indexes for leaderboard queries
CREATE INDEX IF NOT EXISTS idx_strategy_performance_sharpe ON strategy_performance(sharpe_ratio DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_performance_winrate ON strategy_performance(win_rate DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_performance_pnl ON strategy_performance(total_pnl DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_performance_active ON strategy_performance(is_active);

-- Evolution generations tracking
CREATE TABLE IF NOT EXISTS strategy_generations (
    id TEXT PRIMARY KEY,
    parent_id TEXT,
    strategy_id TEXT NOT NULL,
    generation INTEGER NOT NULL,
    generation_type TEXT NOT NULL, -- mutation, crossover, initial
    parameters TEXT NOT NULL, -- JSON object
    fitness_score REAL DEFAULT 0, -- Composite score based on Sharpe, win rate, etc.
    sharpe_ratio REAL,
    win_rate REAL,
    total_pnl REAL,
    max_drawdown REAL,
    is_selected BOOLEAN DEFAULT 0, -- Selected for next generation
    population_rank INTEGER, -- Rank within generation
    created_at INTEGER NOT NULL,
    FOREIGN KEY (parent_id) REFERENCES strategy_ideas(id),
    FOREIGN KEY (strategy_id) REFERENCES strategy_ideas(id)
);

-- Create indexes for evolution queries
CREATE INDEX IF NOT EXISTS idx_strategy_generations_parent ON strategy_generations(parent_id);
CREATE INDEX IF NOT EXISTS idx_strategy_generations_gen ON strategy_generations(generation);
CREATE INDEX IF NOT EXISTS idx_strategy_generations_fitness ON strategy_generations(fitness_score DESC);

-- Market regime history for research correlation
CREATE TABLE IF NOT EXISTS market_regime_history (
    id TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    regime TEXT NOT NULL, -- trending, ranging, volatile
    confidence REAL DEFAULT 0,
    volatility_index REAL,
    trend_strength REAL,
    indicators TEXT, -- JSON object with raw indicators
    started_at INTEGER NOT NULL,
    ended_at INTEGER,
    created_at INTEGER NOT NULL
);

-- Create indexes for regime queries
CREATE INDEX IF NOT EXISTS idx_market_regime_symbol ON market_regime_history(symbol);
CREATE INDEX IF NOT EXISTS idx_market_regime_regime ON market_regime_history(regime);
CREATE INDEX IF NOT EXISTS idx_market_regime_time ON market_regime_history(created_at);

-- Research activity log for audit/debugging
CREATE TABLE IF NOT EXISTS research_activity_log (
    id TEXT PRIMARY KEY,
    activity_type TEXT NOT NULL, -- idea_generated, backtest_started, backtest_completed, evolution_run, etc.
    strategy_id TEXT,
    details TEXT, -- JSON object with activity details
    created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_research_activity_type ON research_activity_log(activity_type);
CREATE INDEX IF NOT EXISTS idx_research_activity_time ON research_activity_log(created_at);

-- Initial data migration: populate strategy_ideas from existing AGGRESSIVE_STRATEGIES
-- This ensures we have baseline strategies to evolve from
INSERT OR IGNORE INTO strategy_ideas (
    id, name, description, type, symbols, timeframe, 
    parameters, entry_conditions, exit_conditions, risk_parameters,
    status, confidence, created_at, updated_at
)
SELECT 
    lower(hex(randomblob(16))),
    'Momentum Surge - 5m',
    'Catch momentum surges on 5-minute candles',
    'TREND_FOLLOWING',
    '["BTC", "ETH", "SOL"]',
    '5m',
    '{"momentumThreshold": 0.02, "volumeSpike": 2.0, "rsiConfirm": 50}',
    '["Price change > 2% in 5m", "Volume spike > 2x average"]',
    '["Momentum fades", "Stop loss / take profit"]',
    '{"maxPositionSize": 0.10, "stopLoss": 0.025, "takeProfit": 0.06, "maxLeverage": 4}',
    'completed',
    0.7,
    strftime('%s', 'now') * 1000,
    strftime('%s', 'now') * 1000
WHERE NOT EXISTS (SELECT 1 FROM strategy_ideas LIMIT 1);
