#!/bin/bash
# Run research engine database migration

cd /home/d/PerpsTrader

# Check if migration already applied
if sqlite3 data/trading.db "SELECT name FROM sqlite_master WHERE type='table' AND name='strategy_ideas';" | grep -q strategy_ideas; then
    echo "Migration 004 already applied (strategy_ideas table exists)"
    exit 0
fi

# Apply migration
sqlite3 data/trading.db << 'EOF'
-- Strategy ideas generated by the research engine
CREATE TABLE IF NOT EXISTS strategy_ideas (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL,
    symbols TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    parameters TEXT NOT NULL,
    entry_conditions TEXT NOT NULL,
    exit_conditions TEXT NOT NULL,
    risk_parameters TEXT NOT NULL,
    confidence REAL DEFAULT 0.5,
    status TEXT DEFAULT 'pending',
    market_regime TEXT,
    parent_strategy_id TEXT,
    generation INTEGER DEFAULT 0,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (parent_strategy_id) REFERENCES strategy_ideas(id)
);

CREATE INDEX IF NOT EXISTS idx_strategy_ideas_status ON strategy_ideas(status);
CREATE INDEX IF NOT EXISTS idx_strategy_ideas_regime ON strategy_ideas(market_regime);
CREATE INDEX IF NOT EXISTS idx_strategy_ideas_created ON strategy_ideas(created_at);

-- Backtest jobs queue
CREATE TABLE IF NOT EXISTS backtest_jobs (
    id TEXT PRIMARY KEY,
    strategy_id TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    priority INTEGER DEFAULT 5,
    candles_count INTEGER DEFAULT 4320,
    results TEXT,
    error_message TEXT,
    sharpe_ratio REAL,
    win_rate REAL,
    total_pnl REAL,
    max_drawdown REAL,
    total_trades INTEGER,
    started_at INTEGER,
    completed_at INTEGER,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (strategy_id) REFERENCES strategy_ideas(id)
);

CREATE INDEX IF NOT EXISTS idx_backtest_jobs_status ON backtest_jobs(status);
CREATE INDEX IF NOT EXISTS idx_backtest_jobs_priority ON backtest_jobs(priority);
CREATE INDEX IF NOT EXISTS idx_backtest_jobs_strategy ON backtest_jobs(strategy_id);

-- Strategy performance leaderboard
CREATE TABLE IF NOT EXISTS strategy_performance (
    id TEXT PRIMARY KEY,
    strategy_id TEXT NOT NULL UNIQUE,
    sharpe_ratio REAL DEFAULT 0,
    win_rate REAL DEFAULT 0,
    total_pnl REAL DEFAULT 0,
    max_drawdown REAL DEFAULT 0,
    profit_factor REAL DEFAULT 0,
    total_trades INTEGER DEFAULT 0,
    average_win REAL DEFAULT 0,
    average_loss REAL DEFAULT 0,
    calmar_ratio REAL DEFAULT 0,
    sortino_ratio REAL DEFAULT 0,
    is_active BOOLEAN DEFAULT 0,
    is_promoted BOOLEAN DEFAULT 0,
    last_backtest_at INTEGER,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (strategy_id) REFERENCES strategy_ideas(id)
);

CREATE INDEX IF NOT EXISTS idx_strategy_performance_sharpe ON strategy_performance(sharpe_ratio DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_performance_winrate ON strategy_performance(win_rate DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_performance_pnl ON strategy_performance(total_pnl DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_performance_active ON strategy_performance(is_active);

-- Evolution generations tracking
CREATE TABLE IF NOT EXISTS strategy_generations (
    id TEXT PRIMARY KEY,
    parent_id TEXT,
    strategy_id TEXT NOT NULL,
    generation INTEGER NOT NULL,
    generation_type TEXT NOT NULL,
    parameters TEXT NOT NULL,
    fitness_score REAL DEFAULT 0,
    sharpe_ratio REAL,
    win_rate REAL,
    total_pnl REAL,
    max_drawdown REAL,
    is_selected BOOLEAN DEFAULT 0,
    population_rank INTEGER,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (parent_id) REFERENCES strategy_ideas(id),
    FOREIGN KEY (strategy_id) REFERENCES strategy_ideas(id)
);

CREATE INDEX IF NOT EXISTS idx_strategy_generations_parent ON strategy_generations(parent_id);
CREATE INDEX IF NOT EXISTS idx_strategy_generations_gen ON strategy_generations(generation);
CREATE INDEX IF NOT EXISTS idx_strategy_generations_fitness ON strategy_generations(fitness_score DESC);

-- Market regime history
CREATE TABLE IF NOT EXISTS market_regime_history (
    id TEXT PRIMARY KEY,
    symbol TEXT NOT NULL,
    regime TEXT NOT NULL,
    confidence REAL DEFAULT 0,
    volatility_index REAL,
    trend_strength REAL,
    indicators TEXT,
    started_at INTEGER NOT NULL,
    ended_at INTEGER,
    created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_market_regime_symbol ON market_regime_history(symbol);
CREATE INDEX IF NOT EXISTS idx_market_regime_regime ON market_regime_history(regime);
CREATE INDEX IF NOT EXISTS idx_market_regime_time ON market_regime_history(created_at);

-- Research activity log
CREATE TABLE IF NOT EXISTS research_activity_log (
    id TEXT PRIMARY KEY,
    activity_type TEXT NOT NULL,
    strategy_id TEXT,
    details TEXT,
    created_at INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_research_activity_type ON research_activity_log(activity_type);
CREATE INDEX IF NOT EXISTS idx_research_activity_time ON research_activity_log(created_at);
EOF

echo "Migration 004 applied successfully!"
