/**
 * Hermes Training Cycle - Mutant Generation & Backtesting
 * Generated by hermes-1 autonomous training loop
 */
import Database from 'better-sqlite3';
import crypto from 'crypto';

const DB_PATH = '/home/d/PerpsTrader/data/trading.db';
const db = new Database(DB_PATH);

interface MutantDef {
  name: string;
  description: string;
  type: string;
  symbols: string[];
  timeframe: string;
  parameters: Record<string, any>;
  entryConditions: string[];
  exitConditions: string[];
  riskParameters: Record<string, any>;
  confidence: number;
  rationale: string;
}

// === ANALYSIS ===
const losingTrades = db.prepare(`
  SELECT symbol, side, COUNT(*) as cnt, 
    ROUND(SUM(CAST(pnl AS REAL)), 4) as total_pnl
  FROM trades WHERE status = 'FILLED' 
  GROUP BY symbol, side HAVING total_pnl < 0
  ORDER BY total_pnl ASC
`).all() as any[];

const winningTrades = db.prepare(`
  SELECT symbol, side, COUNT(*) as cnt, 
    ROUND(SUM(CAST(pnl AS REAL)), 4) as total_pnl
  FROM trades WHERE status = 'FILLED' 
  GROUP BY symbol, side HAVING total_pnl > 0
  ORDER BY total_pnl DESC LIMIT 5
`).all() as any[];

console.log('=== Trade Analysis ===');
console.log('LOSERS:');
losingTrades.forEach(s => console.log(`  ${s.symbol} ${s.side}: PnL=${s.total_pnl}, trades=${s.cnt}`));
console.log('WINNERS:');
winningTrades.forEach(s => console.log(`  ${s.symbol} ${s.side}: PnL=${s.total_pnl}, trades=${s.cnt}`));

// === MUTANT GENERATION ===
const mutants: MutantDef[] = [
  // 1. ETH Tight Mean Reversion (ETH BUY = -$0.28, biggest loser)
  {
    name: "ETH Tight RSI Reversion",
    description: "ETH-specific mean reversion with ultra-tight SL, shorter RSI and BB for faster signals",
    type: "MEAN_REVERSION",
    symbols: ["ETH"],
    timeframe: "15m",
    parameters: { rsiPeriod: 10, oversold: 28, overbought: 72, bbPeriod: 15, bbStdDev: 1.8 },
    entryConditions: ["RSI < 28", "Price below lower BB", "Volume > 1.5x average"],
    exitConditions: ["RSI > 72", "Price above upper BB", "Stop loss hit"],
    riskParameters: { maxPositionSize: 0.02, stopLoss: 0.008, takeProfit: 0.015, maxLeverage: 3 },
    confidence: 0.7,
    rationale: "ETH biggest loser. Tighter risk, shorter lookback, smaller position."
  },
  // 2. SOL Momentum (SOL SELL = +$1.39, best winner)
  {
    name: "SOL Momentum Scalper",
    description: "SOL trend following using EMA crossover with ATR-based stops",
    type: "TREND_FOLLOWING",
    symbols: ["SOL"],
    timeframe: "5m",
    parameters: { emaFast: 8, emaSlow: 21, atrPeriod: 10, atrMultiplier: 1.5 },
    entryConditions: ["EMA8 crosses above EMA21", "ATR below 1.5%", "Volume increasing"],
    exitConditions: ["EMA8 crosses below EMA21", "ATR trailing stop hit", "Take profit 2%"],
    riskParameters: { maxPositionSize: 0.03, stopLoss: 0.012, takeProfit: 0.02, maxLeverage: 5 },
    confidence: 0.75,
    rationale: "SOL sells most profitable. Momentum trend following with tight risk."
  },
  // 3. Breakout with ADX filter
  {
    name: "Volume ADX Breakout",
    description: "BB breakout with strict volume + ADX filter for liquid assets",
    type: "BREAKOUT",
    symbols: ["BTC", "ETH", "SOL"],
    timeframe: "1h",
    parameters: { bbPeriod: 20, bbStdDev: 2.0, volumeThreshold: 2.5, adxPeriod: 14, adxMin: 20 },
    entryConditions: ["Price closes above upper BB", "Volume > 2.5x avg", "ADX > 20"],
    exitConditions: ["Price closes below middle BB", "ADX < 15", "Stop loss 2.5%"],
    riskParameters: { maxPositionSize: 0.03, stopLoss: 0.025, takeProfit: 0.08, maxLeverage: 4 },
    confidence: 0.65,
    rationale: "Breakout strategies need volume+ADX confirmation to avoid false signals."
  },
  // 4. kPEPE momentum (kPEPE BUY = +$0.30)
  {
    name: "kPEPE Momentum Fade",
    description: "kPEPE mean reversion after momentum spikes, tighter TP than current",
    type: "MEAN_REVERSION",
    symbols: ["kPEPE"],
    timeframe: "5m",
    parameters: { rsiPeriod: 7, oversold: 25, overbought: 80, emaPeriod: 9 },
    entryConditions: ["RSI(7) < 25", "Price > 3% below EMA9", "Volume spike > 2x"],
    exitConditions: ["RSI > 50", "Price crosses EMA9", "Take profit 1%"],
    riskParameters: { maxPositionSize: 0.01, stopLoss: 0.01, takeProfit: 0.01, maxLeverage: 3 },
    confidence: 0.6,
    rationale: "kPEPE profitable but 42 trades for $0.30. Tighter TP to improve per-trade return."
  },
  // 5. LINK accumulation (LINK BUY = +$0.14)
  {
    name: "LINK EMA Cross Momentum",
    description: "LINK EMA crossover with volume confirmation, optimized for the asset's behavior",
    type: "TREND_FOLLOWING",
    symbols: ["LINK"],
    timeframe: "15m",
    parameters: { emaFast: 12, emaSlow: 26, rsiConfirm: 14, volumeConfirm: 1.8 },
    entryConditions: ["EMA12 > EMA26", "RSI(14) between 40-70", "Volume > 1.8x avg"],
    exitConditions: ["EMA12 < EMA26", "RSI < 35", "Stop loss 2%"],
    riskParameters: { maxPositionSize: 0.03, stopLoss: 0.02, takeProfit: 0.04, maxLeverage: 4 },
    confidence: 0.6,
    rationale: "LINK consistently profitable (65 buys, +$0.14). Formalize the pattern."
  },
];

// === INSERT MUTANTS ===
const now = new Date().toISOString();
const insertIdea = db.prepare(`
  INSERT OR REPLACE INTO strategy_ideas 
  (id, name, description, type, symbols, timeframe, parameters, 
   entry_conditions, exit_conditions, risk_parameters, confidence, 
   rationale, status, market_context, created_at, updated_at, params_hash)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

let inserted = 0;
for (const m of mutants) {
  const id = `hermes-mutant-${Date.now()}-${inserted}`;
  const paramsStr = JSON.stringify(m.parameters);
  const riskStr = JSON.stringify(m.riskParameters);
  const paramsHash = crypto.createHash('sha256').update(paramsStr + riskStr).digest('hex');
  
  const existing = db.prepare("SELECT id FROM strategy_ideas WHERE params_hash = ?").get(paramsHash);
  if (existing) {
    console.log(`SKIP ${m.name}: duplicate params`);
    continue;
  }
  
  try {
    insertIdea.run(
      id, m.name, m.description, m.type, 
      JSON.stringify(m.symbols), m.timeframe, paramsStr,
      JSON.stringify(m.entryConditions), JSON.stringify(m.exitConditions),
      riskStr, m.confidence, m.rationale,
      'PENDING', 
      JSON.stringify({regime: 'VOLATILE', generatedBy: 'hermes-1', cycle: now}),
      now, now, paramsHash
    );
    console.log(`INSERT ${m.name}: ${id}`);
    inserted++;
  } catch (e: any) {
    console.log(`ERROR ${m.name}: ${e.message}`);
  }
}
console.log(`\nMutants inserted: ${inserted}/${mutants.length}`);

// === RUN BACKTESTS ===
(async () => {
console.log('\n=== Running Backtests ===');

try {
  const { BacktestEngine } = await import('../src/backtest/enhanced-backtest');

  for (const m of mutants) {
    // Load market data
    const cutoffTime = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(); // 5d
    const marketData: any[] = [];
    
    for (const symbol of m.symbols.slice(0, 3)) {
      const rows = db.prepare(
        'SELECT symbol, timestamp, open, high, low, close, volume FROM market_data WHERE symbol = ? AND timestamp >= ? ORDER BY timestamp ASC'
      ).all(symbol, cutoffTime) as any[];
      
      for (const row of rows) {
        marketData.push({
          symbol: row.symbol,
          timestamp: new Date(row.timestamp),
          open: row.open,
          high: row.high,
          low: row.low,
          close: row.close,
          volume: row.volume,
        });
      }
    }

    console.log(`\n${m.name}: ${marketData.length} candles (${m.symbols.slice(0, 3).join(', ')})`);
    
    if (marketData.length < 100) {
      console.log('  SKIP: insufficient data');
      continue;
    }

    const strategy = {
      id: `hermes-test-${m.name.replace(/\s+/g, '-').toLowerCase()}`,
      name: m.name,
      type: m.type,
      symbols: m.symbols,
      timeframe: m.timeframe,
      parameters: m.parameters,
      entryConditions: m.entryConditions,
      exitConditions: m.exitConditions,
      riskParameters: m.riskParameters,
    };

    const engine = new BacktestEngine({
      initialCapital: 10000,
      commissionRate: 0.0005,
      slippageBps: 5,
    });

    try {
      const result = await engine.runBacktest(strategy as any, marketData as any);
      
      const totalReturn = ((result.finalCapital - result.initialCapital) / result.initialCapital * 100);
      const sharpe = result.sharpeRatio || 0;
      const winRate = result.winRate || 0;
      const maxDD = result.maxDrawdown || 0;
      const trades = result.totalTrades || 0;
      
      console.log(`  Return: ${totalReturn.toFixed(2)}%`);
      console.log(`  Sharpe: ${sharpe.toFixed(2)}`);
      console.log(`  Win Rate: ${(winRate * 100).toFixed(1)}%`);
      console.log(`  Max DD: ${(maxDD * 100).toFixed(2)}%`);
      console.log(`  Trades: ${trades}`);

      // Store backtest result
      const resultId = `bt-${Date.now()}-${m.name.replace(/\s+/g, '-').toLowerCase()}`;
      db.prepare(`
        INSERT INTO backtest_results 
        (id, strategyId, periodStart, periodEnd, initialCapital, finalCapital,
         totalReturn, annualizedReturn, sharpeRatio, maxDrawdown, winRate,
         totalTrades, trades, metrics, createdAt)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `).run(
        resultId, strategy.id, cutoffTime, now,
        10000, result.finalCapital,
        totalReturn, totalReturn * 73, // ~5d annualized
        sharpe, maxDD, winRate,
        trades, JSON.stringify(result.trades || []),
        JSON.stringify({ profitFactor: (result as any).profitFactor || 0 }),
        now
      );

      // Update idea status
      db.prepare("UPDATE strategy_ideas SET status = 'COMPLETED' WHERE name = ?").run(m.name);
      
      console.log(`  SAVED: ${resultId}`);
    } catch (btErr: any) {
      console.log(`  BACKTEST ERROR: ${btErr.message?.substring(0, 200)}`);
    }
  }
} catch (importErr: any) {
  console.log(`Cannot import BacktestEngine: ${importErr.message}`);
  console.log('Mutants saved to strategy_ideas for later backtesting.');
}

// === EVALUATION & PROMOTION ===
console.log('\n=== Evaluation ===');
const allResults = db.prepare(`
  SELECT strategyId, ROUND(totalReturn, 2) as ret, ROUND(sharpeRatio, 2) as sharpe, 
    ROUND(winRate * 100, 1) as wr, ROUND(maxDrawdown * 100, 2) as dd, totalTrades
  FROM backtest_results ORDER BY sharpeRatio DESC
`).all() as any[];

console.log(`Total backtest results: ${allResults.length}`);
allResults.forEach((r, i) => {
  const pass = r.sharpe > 0.5 && r.wr > 45 && r.dd < 20 && r.totalTrades > 5;
  console.log(`  ${i+1}. ${r.strategyId}: Sharpe=${r.sharpe}, Ret=${r.ret}%, WR=${r.wr}%, DD=${r.dd}%, Trades=${r.totalTrades} ${pass ? 'PASS' : 'FAIL'}`);
});

// Find best mutant that passes the gate
const bestResult = allResults.find(r => 
  r.sharpe > 0.5 && r.wr > 45 && r.dd < 20 && r.totalTrades > 5
);

if (bestResult) {
  console.log(`\nBest candidate: ${bestResult.strategyId} (Sharpe=${bestResult.sharpe})`);
  // Find the corresponding mutant
  const mutantName = bestResult.strategyId.replace('hermes-test-', '').replace(/-/g, ' ');
  const idea = db.prepare("SELECT * FROM strategy_ideas WHERE name LIKE ?").get(`%${mutantName.split(' ')[0]}%`) as any;
  if (idea) {
    console.log(`  Corresponding idea: ${idea.name}`);
    console.log(`  Parameters: ${idea.parameters}`);
    console.log(`  Risk: ${idea.risk_parameters}`);
    console.log(`  RECOMMENDATION: Promote to active (paper trading)`);
  }
} else {
  console.log('\nNo mutants passed the promotion gate (Sharpe > 0.5, WR > 45%, DD < 20%, Trades > 5)');
}

// === CURRENT LIVE PERFORMANCE BASELINE ===
console.log('\n=== Active Strategy Performance Baseline ===');
const activePerf = db.prepare(`
  SELECT s.name, s.type, s.symbols,
    COUNT(t.id) as trades,
    SUM(CASE WHEN t.status='FILLED' THEN 1 ELSE 0 END) as filled,
    SUM(CASE WHEN t.status='CANCELLED' THEN 1 ELSE 0 END) as cancelled,
    ROUND(SUM(CASE WHEN t.status='FILLED' THEN CAST(t.pnl AS REAL) ELSE 0 END), 4) as pnl
  FROM strategies s
  LEFT JOIN trades t ON t.strategy_id = s.id
  WHERE s.isActive = 1
  GROUP BY s.id
  ORDER BY pnl DESC
`).all() as any[];

activePerf.forEach(s => {
  console.log(`  ${s.name}: trades=${s.trades}, filled=${s.filled}, cancelled=${s.cancelled}, pnl=${s.pnl}`);
});

db.close();
console.log('\n=== Cycle Complete ===');
})();
