/**
 * Hermes Training Cycle - Backtest Runner
 * Loads market data, backtests mutant strategies, outputs JSON results
 */
import { BacktestEngine } from '../src/backtest/enhanced-backtest';
import { Strategy } from '../src/shared/types';
import Database from 'better-sqlite3';

const SYMBOLS = ['SOL', 'BTC', 'LINK', 'BCH', 'ZEC', 'kPEPE', 'NEAR'];
const CUTOFF_7D = '2026-03-13T00:00:00.000Z';
const CUTOFF_30D = '2026-02-18T00:00:00.000Z';

interface MutantDef {
  id: string;
  name: string;
  type: Strategy['type'];
  symbols: string[];
  parameters: Record<string, any>;
  riskParameters: { maxPositionSize: number; stopLoss: number; takeProfit: number; maxLeverage: number };
}

const MUTANTS: MutantDef[] = [
  {
    id: 'ecd2690b',
    name: 'RSI Tight Alpha Symbols v2',
    type: 'MEAN_REVERSION',
    symbols: ['ZEC', 'SOL', 'kPEPE', 'LINK', 'BCH'],
    parameters: { rsiPeriod: 10, oversold: 22, overbought: 78, bbPeriod: 18, bbStdDev: 2.0, volumeFilter: 1.2 },
    riskParameters: { stopLoss: 0.025, takeProfit: 0.05, maxPositionSize: 0.04, maxLeverage: 3 }
  },
  {
    id: '7ab834da',
    name: 'SOL EMA Momentum Scalp',
    type: 'TREND_FOLLOWING',
    symbols: ['SOL'],
    parameters: { emaFast: 9, emaSlow: 21, rsiConfirmation: 55, atrPeriod: 14, atrMultiplier: 1.5 },
    riskParameters: { stopLoss: 0.015, takeProfit: 0.03, maxPositionSize: 0.06, maxLeverage: 4 }
  },
  {
    id: '733c3132',
    name: 'BCH RSI Bollinger Bounce',
    type: 'MEAN_REVERSION',
    symbols: ['BCH'],
    parameters: { rsiPeriod: 12, oversold: 28, overbought: 72, bbPeriod: 20, bbStdDev: 2.0 },
    riskParameters: { stopLoss: 0.02, takeProfit: 0.02, maxPositionSize: 0.05, maxLeverage: 3 }
  },
  {
    id: 'c8000c1a',
    name: 'LINK ATR Breakout v3',
    type: 'TREND_FOLLOWING',
    symbols: ['LINK'],
    parameters: { atrPeriod: 10, atrBreakoutMult: 1.8, emaTrend: 50, volumeConfirm: 1.5 },
    riskParameters: { stopLoss: 0.015, takeProfit: 0.025, maxPositionSize: 0.05, maxLeverage: 4 }
  },
  {
    id: 'f9f221b6',
    name: 'Multi-Symbol RSI Adaptive v2',
    type: 'MEAN_REVERSION',
    symbols: ['BTC', 'SOL', 'LINK', 'BCH', 'ZEC', 'kPEPE', 'NEAR'],
    parameters: { rsiPeriod: 14, oversold: 25, overbought: 75, bbPeriod: 20, bbStdDev: 2.0, cooldownBars: 3 },
    riskParameters: { stopLoss: 0.02, takeProfit: 0.03, maxPositionSize: 0.03, maxLeverage: 3 }
  }
];

function makeStrategy(m: MutantDef): Strategy {
  return {
    id: m.id,
    name: m.name,
    description: `Hermes mutant cycle 2026-03-20: ${m.name}`,
    type: m.type,
    symbols: m.symbols,
    timeframe: '15m',
    parameters: m.parameters,
    entryConditions: ['Auto-generated by Hermes training cycle'],
    exitConditions: [`SL ${m.riskParameters.stopLoss}`, `TP ${m.riskParameters.takeProfit}`],
    riskParameters: m.riskParameters,
    isActive: false,
    performance: { totalTrades: 0, winningTrades: 0, losingTrades: 0, winRate: 0, totalPnL: 0, sharpeRatio: 0, maxDrawdown: 0, averageWin: 0, averageLoss: 0, profitFactor: 0 },
    createdAt: new Date(),
    updatedAt: new Date(),
  };
}

async function main() {
  const db = new Database('./data/trading.db');
  const results: any[] = [];

  for (const mutant of MUTANTS) {
    const strategy = makeStrategy(mutant);
    console.log(`\n=== Backtesting: ${strategy.name} (${strategy.symbols.join(',')}) ===`);

    // Load market data for each symbol the strategy covers
    for (const symbol of strategy.symbols) {
      // Sample every 15 minutes (900s) to match strategy timeframe
      const rows = db.prepare(`
        SELECT symbol, timestamp, open, high, low, close, volume, vwap, bid, ask, bidSize, askSize
        FROM market_data
        WHERE symbol = ? AND timestamp >= ?
        GROUP BY (CAST(strftime('%s', timestamp) AS INTEGER) / 900)
        ORDER BY timestamp ASC
      `).all(symbol, CUTOFF_7D) as any[];

      if (rows.length === 0) {
        console.log(`  ${symbol}: NO DATA, skipping`);
        continue;
      }

      const marketData = rows.map(r => ({ ...r, timestamp: new Date(r.timestamp) }));
      const engine = new BacktestEngine({
        initialCapital: 10000,
        commissionRate: 0.0005,
        slippageBps: 5,
        randomSeed: 42,
      });

      try {
        // Run with this symbol only
        const singleSymbolStrategy = { ...strategy, symbols: [symbol] };
        const result = await engine.runBacktest(singleSymbolStrategy, marketData);
        const pass = (result.sharpeRatio > 0.5) && (result.winRate > 45) && (result.maxDrawdown < 20);
        console.log(`  ${symbol}: Sharpe=${(result.sharpeRatio ?? 0).toFixed(4)} WR=${(result.winRate ?? 0).toFixed(1)}% DD=${(result.maxDrawdown ?? 0).toFixed(2)}% Trades=${result.totalTrades} Return=${(result.totalReturn ?? 0).toFixed(2)}% PF=${(result.profitFactor ?? 0).toFixed(2)} ${pass ? 'PASS' : 'FAIL'}`);

        results.push({
          strategyId: mutant.id,
          strategyName: strategy.name,
          strategyType: strategy.type,
          symbol,
          sharpe: result.sharpeRatio ?? 0,
          winRate: result.winRate ?? 0,
          maxDrawdown: result.maxDrawdown ?? 0,
          totalTrades: result.totalTrades ?? 0,
          totalReturn: result.totalReturn ?? 0,
          profitFactor: result.profitFactor ?? 0,
          pass,
          candles: marketData.length,
          timestamp: new Date().toISOString(),
        });
      } catch (e: any) {
        console.error(`  ${symbol}: FAILED - ${e.message}`);
        results.push({
          strategyId: mutant.id,
          strategyName: strategy.name,
          symbol,
          error: e.message,
          pass: false,
          timestamp: new Date().toISOString(),
        });
      }
    }
  }

  // Summary
  const passed = results.filter(r => r.pass);
  const failed = results.filter(r => !r.pass);
  console.log(`\n=== SUMMARY ===`);
  console.log(`Total runs: ${results.length}`);
  console.log(`Passed: ${passed.length}`);
  console.log(`Failed: ${failed.length}`);
  if (passed.length > 0) {
    console.log(`\nBest performers:`);
    passed.sort((a, b) => (b.sharpe ?? 0) - (a.sharpe ?? 0));
    for (const p of passed.slice(0, 5)) {
      console.log(`  ${p.strategyName} [${p.symbol}] Sharpe=${p.sharpe.toFixed(4)} WR=${p.winRate.toFixed(1)}% DD=${p.maxDrawdown.toFixed(2)}%`);
    }
  }

  // Output JSON
  console.log('\n=== JSON_OUTPUT_START ===');
  console.log(JSON.stringify(results, null, 2));
  console.log('=== JSON_OUTPUT_END ===');

  db.close();
}

main().catch(e => { console.error('Fatal:', e); process.exit(1); });
