#!/usr/bin/env node
/*
 * OpenClaw Wallet Access Utility
 * Local-only wallet access for ClawDBot/OpenClaw integrations.
 */

const fs = require('fs');
const path = require('path');
const { privateKeyToAccount } = require('viem/accounts');
const { Keypair } = require('@solana/web3.js');

const DEFAULT_STORE = 'config/openclaw/wallets.json';
const LEGACY_STORE = 'config/agent-wallets.json';
const DEFAULT_ENV_OUTPUT = 'config/openclaw/clawdbot.wallets.env';

function resolveStorePath() {
  if (process.env.SAFEKEEPING_WALLET_STORE_PATH) {
    return path.isAbsolute(process.env.SAFEKEEPING_WALLET_STORE_PATH)
      ? process.env.SAFEKEEPING_WALLET_STORE_PATH
      : path.resolve(process.cwd(), process.env.SAFEKEEPING_WALLET_STORE_PATH);
  }

  const preferred = path.resolve(process.cwd(), DEFAULT_STORE);
  if (fs.existsSync(preferred)) {
    return preferred;
  }

  const legacy = path.resolve(process.cwd(), LEGACY_STORE);
  if (fs.existsSync(legacy)) {
    return legacy;
  }

  return preferred;
}

function usage() {
  console.log('Usage: node scripts/openclaw-wallets.js <command> [args]');
  console.log('');
  console.log('Commands:');
  console.log('  addresses                 Show chain funding addresses');
  console.log('  permissions               Validate wallet store file/dir permissions');
  console.log('  export-env [outputPath]   Write ClawDBot env file with private keys');
}

function readWalletStore(storePath) {
  if (!fs.existsSync(storePath)) {
    throw new Error(`Wallet store not found at ${storePath}. Run: npm run wallets:setup`);
  }

  const parsed = JSON.parse(fs.readFileSync(storePath, 'utf8'));
  if (!parsed || parsed.version !== 1 || !parsed.wallets) {
    throw new Error(`Invalid wallet store format at ${storePath}`);
  }

  return parsed;
}

function deriveAddresses(store) {
  const addresses = {};

  if (store.wallets.ethereum?.privateKey) {
    addresses.ethereum = privateKeyToAccount(store.wallets.ethereum.privateKey).address;
  }

  if (store.wallets.bsc?.privateKey) {
    addresses.bsc = privateKeyToAccount(store.wallets.bsc.privateKey).address;
  }

  if (store.wallets.solana?.secretKeyBase64) {
    const secretKey = Uint8Array.from(Buffer.from(store.wallets.solana.secretKeyBase64, 'base64'));
    addresses.solana = Keypair.fromSecretKey(secretKey).publicKey.toBase58();
  }

  return addresses;
}

function permissionsStatus(storePath) {
  const stat = fs.statSync(storePath);
  const fileMode = stat.mode & 0o777;
  const fileSecure = (fileMode & 0o077) === 0;

  const dirPath = path.dirname(storePath);
  const dirStat = fs.statSync(dirPath);
  const dirMode = dirStat.mode & 0o777;
  const dirSecure = (dirMode & 0o077) === 0;

  return {
    fileMode,
    fileSecure,
    dirPath,
    dirMode,
    dirSecure,
  };
}

function formatOctal(mode) {
  return mode.toString(8).padStart(3, '0');
}

function writeClawDbotEnv(storePath, store, outputPathArg) {
  const outputPath = outputPathArg
    ? (path.isAbsolute(outputPathArg) ? outputPathArg : path.resolve(process.cwd(), outputPathArg))
    : path.resolve(process.cwd(), DEFAULT_ENV_OUTPUT);

  const addresses = deriveAddresses(store);
  const lines = [];
  lines.push(`# Generated by scripts/openclaw-wallets.js on ${new Date().toISOString()}`);
  lines.push('# Restrict file permissions to owner-only.');
  lines.push(`OPENCLAW_WALLET_STORE_PATH=${storePath}`);
  lines.push(`OPENCLAW_ETH_ADDRESS=${addresses.ethereum || ''}`);
  lines.push(`OPENCLAW_BSC_ADDRESS=${addresses.bsc || ''}`);
  lines.push(`OPENCLAW_SOLANA_ADDRESS=${addresses.solana || ''}`);
  lines.push(`OPENCLAW_ETH_PRIVATE_KEY=${store.wallets.ethereum?.privateKey || ''}`);
  lines.push(`OPENCLAW_BSC_PRIVATE_KEY=${store.wallets.bsc?.privateKey || ''}`);
  lines.push(`OPENCLAW_SOLANA_SECRET_KEY_BASE64=${store.wallets.solana?.secretKeyBase64 || ''}`);
  lines.push('');
  lines.push('# Optional compatibility aliases');
  lines.push(`ETH_PRIVATE_KEY=${store.wallets.ethereum?.privateKey || ''}`);
  lines.push(`BSC_PRIVATE_KEY=${store.wallets.bsc?.privateKey || ''}`);
  lines.push(`SOLANA_SECRET_KEY_BASE64=${store.wallets.solana?.secretKeyBase64 || ''}`);
  lines.push(`SOLANA_SECRET_KEY=${store.wallets.solana?.secretKeyBase64 || ''}`);

  const outputDir = path.dirname(outputPath);
  fs.mkdirSync(outputDir, { recursive: true, mode: 0o700 });
  fs.chmodSync(outputDir, 0o700);
  fs.writeFileSync(outputPath, `${lines.join('\n')}\n`, { mode: 0o600 });
  fs.chmodSync(outputPath, 0o600);

  return outputPath;
}

function main() {
  const command = process.argv[2] || 'addresses';
  const storePath = resolveStorePath();

  if (command === 'help' || command === '--help' || command === '-h') {
    usage();
    return;
  }

  const store = readWalletStore(storePath);

  if (command === 'addresses') {
    const addresses = deriveAddresses(store);
    console.log('OpenClaw Wallet Addresses');
    console.log(`Store: ${storePath}`);
    console.log(`ethereum: ${addresses.ethereum || 'not configured'}`);
    console.log(`bsc: ${addresses.bsc || 'not configured'}`);
    console.log(`solana: ${addresses.solana || 'not configured'}`);
    return;
  }

  if (command === 'permissions') {
    const status = permissionsStatus(storePath);
    console.log(`wallet file: ${storePath} mode ${formatOctal(status.fileMode)} ${status.fileSecure ? 'OK' : 'TOO OPEN'}`);
    console.log(`wallet dir:  ${status.dirPath} mode ${formatOctal(status.dirMode)} ${status.dirSecure ? 'OK' : 'TOO OPEN'}`);
    if (!status.fileSecure || !status.dirSecure) {
      process.exitCode = 2;
    }
    return;
  }

  if (command === 'export-env') {
    const outputPath = writeClawDbotEnv(storePath, store, process.argv[3]);
    console.log(`Wrote OpenClaw env file: ${outputPath}`);
    return;
  }

  usage();
  process.exitCode = 1;
}

try {
  main();
} catch (error) {
  console.error(`[openclaw-wallets] ${error.message}`);
  process.exit(1);
}
